fix: shop name alignment fixed
kirananto/vyap pull request #196
Opened 2022-01-16 18:33 UTC by djsreeraj

2022-01-19 12:22 UTC, kirananto requested changes

2022-01-19 12:22 UTC, kirananto commented on src/Pages/ChatView/PlaceOrder/index.tsx
> +        isValidCart && setPaymentModalVisible(true)
Why this approach ? Why not check it before submit ?

2022-01-19 12:40 UTC, djsreeraj commented on src/Pages/ChatView/PlaceOrder/index.tsx
> +        isValidCart && setPaymentModalVisible(true)
this submit is just to proceed to the modal, final submit is inside the modal code

2022-01-19 12:47 UTC, kirananto commented on src/Pages/ChatView/PlaceOrder/index.tsx
> +        isValidCart && setPaymentModalVisible(true)
Why is it not displayed by default ? Let it be displayed by default. 
Why modal ? Not inline in the page ?

2022-01-19 16:45 UTC, djsreeraj commented on src/Pages/ChatView/PlaceOrder/index.tsx
> +        isValidCart && setPaymentModalVisible(true)
not clear bro, need to talk on it

2022-01-21 01:46 UTC, kirananto commented on src/Pages/ChatView/PlaceOrder/index.tsx
> +        isValidCart && setPaymentModalVisible(true)
Let's talk more on this today

2022-01-21 04:34 UTC, djsreeraj commented on src/Pages/ChatView/PlaceOrder/index.tsx
> +        isValidCart && setPaymentModalVisible(true)
sure

2022-01-21 13:45 UTC, kirananto commented on src/Pages/ChatView/PlaceOrder/index.tsx
> +        isValidCart && setPaymentModalVisible(true)
Nvm this also works. we can merge this approach

2022-01-22 09:11 UTC, merged