Sreeraj/feature : improved print for shopwise orders
kirananto/vyap pull request #265
Opened 2022-02-27 07:05 UTC by djsreeraj

2022-02-28 13:17 UTC, kirananto commented
Also along with that there's lot of linting and intendation errors, can you fix it also along with that
use `yarn lint:fix`

2022-02-28 13:20 UTC, kirananto requested changes

2022-02-28 13:20 UTC, kirananto commented on public/index.css
> +    display: none;
Why are we hiding the scrollbar ?

2022-02-28 13:20 UTC, kirananto commented on src/Pages/Reports/ShopReports/ShopReports.tsx
> +    // const [loading, setLoading] = useState(true)
Add a loading state for the same, so that until the data is loaded, user is aware that something is happening

2022-02-28 13:20 UTC, kirananto commented on src/Pages/Reports/ShopReports/ShopReports.tsx
>                      <p className='pl-5'>{orderCount} Orders</p>
Can you check this part in the dark mode, i don't see any dark mode text colors here.

2022-02-28 13:29 UTC, djsreeraj commented on public/index.css
> +    display: none;
scollbar line is coming in print page

2022-02-28 13:52 UTC, djsreeraj commented on src/Pages/Reports/ShopReports/ShopReports.tsx
>                      <p className='pl-5'>{orderCount} Orders</p>
dark:text-slate-200'

2022-02-28 15:44 UTC, kirananto commented on public/index.css
> +    display: none;
Can you add print css then ?

```css
 @media print {
     Your css here
 }
 ```

2022-03-01 02:20 UTC, kirananto commented
![image](https://user-images.githubusercontent.com/12209601/156092403-04cc0051-a803-4c4e-aa9d-bb2ddc1d1f97.png)


More lint fixes, Also sync with latest develop

2022-03-01 06:29 UTC, merged