Sreeraj/feature : added report filters in shopwise reports
kirananto/vyap pull request #326
Opened 2022-03-26 19:00 UTC by djsreeraj

2022-03-29 07:39 UTC, djsreeraj commented
![](https://github.trello.services/images/mini-trello-icon.png) [Report Filtering balance](https://trello.com/c/uwPohAd6/341-report-filtering-balance)

2022-03-30 09:02 UTC, kirananto requested changes

2022-03-30 09:02 UTC, kirananto commented on src/Pages/Reports/ShopReports/ShopReports.tsx
> +                        setFilterValue(FILTERS_VALUES.YESTERDAY)
Why duplicate values ? Can you use a single state to denote this ? 
We should have only one source of truth, this could lead to inconsistencies at later points in time

2022-03-30 09:02 UTC, kirananto commented on src/Pages/Reports/ProductReports/ProductReports.tsx
> +                    onClick={() => {
Why duplicate values ? Can you use a single state to denote this ?
We should have only one source of truth, this could lead to inconsistencies at later points in time

2022-03-30 09:02 UTC, kirananto commented on src/Pages/Reports/ShopReports/ShopReports.tsx
> +        return <div className="flex flex-col absolute p-2 bg-white dark:bg-slate-700 w-[50vw]">
filterOptions looks similar to that in product reports, can you DRY out the code here ?

2022-03-30 09:02 UTC, kirananto commented on src/Pages/Reports/ShopReports/ShopReports.tsx
> +        return new Date().toISOString().split('T')[0]
You could use date manipulation functions here, In this case we might be discarding the edge cases that might be caused due to timezone diff, please verify this case as well

2022-03-30 11:30 UTC, kirananto commented
Build failure. @djsreeraj  can you check ?

2022-04-02 16:08 UTC, kirananto approved these changes

2022-04-02 16:09 UTC, merged